name: Deploy Subscriber 1 AWS Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-subscriber1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Subscriber 1 Lambda Function
      run: |
        zip subscriber1-lambda.zip lambda_function.py
        aws lambda update-function-code \
          --function-name Subscriber1Function \
          --zip-file fileb://subscriber1-lambda.zip
